name: Jira Issue Sync

on:
  issues:
    types: [opened, closed, deleted, reopened]
  issue_comment:
    types: [created]

env:
  EPIC_LINK: "TF-3484"

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # Conditionally change the Epic link if the issue contains the bug label
      # customfield_10008 is the epic link
      - name: Is this a bug
        run: echo "EPIC_LINK=TF-7331" >> $GITHUB_ENV
        if: contains(github.event.issue.labels.*.name, 'bug')

      - name: call-workflow
        uses: ./.github/workflows/jira-issue-sync.yml
        with:
          project: TF
          issue-extra-fields: |
            { "customfield_10091": ["TF-CLI"],
              "customfield_10008": "${{ env.EPIC_LINK }}"
              "labels": "${{ github.event.repository.name }}"
            }
        secrets: inherit
