name: Jira Issue Sync

on:
  issues:
    types: [opened, closed, deleted, reopened]
  issue_comment:
    types: [created]

env:
  EPIC_LINK_BUG: "TF-7331"
  EPIC_LINK_FEATURE: "TF-3484"

jobs:
  call-workflow:
    uses: ./.github/workflows/jira-issue-sync.yml
    with:
      project: TF
      issue-extra-fields: |
        { "customfield_10091": ["TF-CLI"],
          "customfield_10008": "${{ contains(github.event.issue.labels.*.name, 'bug') && github.env.EPIC_LINK_BUG || github.env.EPIC_LINK_FEATURE }}",
          "labels": "${{ github.event.repository.name }}"
        }
    secrets: inherit
