name: Jira Issue Sync

on:
  issues:
    types: [opened, closed, deleted, reopened]
  issue_comment:
    types: [created]

jobs:
  call-workflow:
    uses: ./.github/workflows/jira-issue-sync.yml
    with:
      project: TF
      issue-extra-fields: |
        { "customfield_10091": ["TF-CLI"],
          "customfield_10008": "${{ contains(github.event.issue.labels.*.name, 'bug') && 'Bugs in terraform-provider-tfe' || 'terraform-provider-tfe Feature Requests' }}",
          "labels": "${{ github.event.repository.name }}"
        }
    secrets: inherit
