name: Jira PR Transition

on:
  pull_request:
    types: [opened, closed, reopened, converted_to_draft]

jobs:
  call-workflow:
    uses: ./.github/workflows/jira-pr-transition.yml
    secrets: inherit
