name: Jira Issue Sync

on:
  issues:
    types: [opened, closed, deleted, reopened]
  pull_request_target:
    types: [opened, closed, reopened]
  issue_comment:
    types: [created]

jobs:
  call-workflow:
    uses: ./.github/workflows/jira-issue-sync.yml
    with:
      github-team: Terraform-Enterprise
      project: TF
      issue-extra-fields: |
        { "customfield_10091": ["TF-CLI"] }
    secrets: inherit
