name: Jira Issue PR Transition

on:
  workflow_call:

jobs:
  pr-transition:
    runs-on: ubuntu-latest
    steps:
      - name: Login
        uses: atlassian/gajira-login@v2.0.0
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      - name: Find in branch name
        id: search
        uses: atlassian/gajira-find-issue-key@v2.0.2 # "v3" seems broken
        with:
          string: ${{ github.head_ref }}
          from: ""
      - name: Transition to Development Complete
        if: steps.search.outputs.issue != null && github.event.action == 'closed' && github.event.pull_request.merged == true
        uses: atlassian/gajira-transition@v3
        with:
          transition: "Development Complete"
      - name: Transition to In Review
        if: steps.search.outputs.issue != null && (github.event.action == 'opened' || github.event.action == 'reopened')
        uses: atlassian/gajira-transition@v3
        with:
          issue: ${{ steps.search.outputs.issue }}
          transition: "In Review"
