name: Jira Issue PR Transition

on:
  workflow_call:

jobs:
  pr-transition:
    runs-on: ubuntu-latest
    steps:
      - name: Login
        uses: atlassian/gajira-login@v2.0.0
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      - name: Find in branch name
        id: search
        uses: atlassian/gajira-find-issue-key@v3
        with:
          string: ${{ github.head_ref }}
          from: ""
      - name: Transition Issue
        id: transition
        if: steps.search.outputs.issue
        uses: tuanddd/jira-automate-transition@v1.0.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          column-to-move-to-when-review-requested: In Review
          column-to-move-to-when-changes-requested: In Progress
          column-to-move-to-when-merged: Development Complete
          jira-issue-id: ${{ steps.search.outputs.issue }}

